<Setting>:
    md_bg_color: 1,1,1,1
    MDBoxLayout:
        orientation: 'vertical'
        padding: '30dp', '20dp'
        MDFlatButton:
            text: 'Log out'
            md_bg_color: ("#ff1420")
            theme_text_color: "Custom"
            text_color: 1,1,1,1
            pos_hint: {'right': 1}
            on_release:
                root.parent.parent.parent.parent.manager.transition.direction = "right" 
                root.parent.parent.parent.parent.manager.current = 'login'
