from screens.calcu import Calcu
from screens.splash import Splash
from screens.login import Login
from screens.botnav import Botnav
from screens.home import *
from screens.calcu import *
from screens.cabaidet import *
from screens.setting import *
from screens.signup import *
from screens.stoploss import *
from screens.profile import *
from screens.changepass import *